//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATAa
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEvent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblEvent()
        {
            this.tblComments = new HashSet<tblComment>();
        }
    
        public int eventNumber { get; set; }
        public string details { get; set; }
        public System.DateTime event_date { get; set; }
        public System.TimeSpan event_time { get; set; }
        public decimal latitude { get; set; }
        public decimal longitude { get; set; }
        public Nullable<bool> event_status { get; set; }
        public string picture { get; set; }
        public int userId { get; set; }
        public int serialTypeNumber { get; set; }
        public int country_number { get; set; }
        public int area_number { get; set; }
    
        public virtual tblArea tblArea { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblComment> tblComments { get; set; }
        public virtual tblType tblType { get; set; }
        public virtual tblEvent tblEvents1 { get; set; }
        public virtual tblEvent tblEvent1 { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
