//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATAa
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStakeholder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblStakeholder()
        {
            this.tblTraveleres = new HashSet<tblTravelere>();
        }
    
        public int stakeholdersId { get; set; }
        public Nullable<bool> approved { get; set; }
        public System.DateTime approvelDate { get; set; }
        public string stakeholderType { get; set; }
    
        public virtual tblUser tblUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTravelere> tblTraveleres { get; set; }
    }
}
