//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATAa
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTravelere
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblTravelere()
        {
            this.tblLocations = new HashSet<tblLocation>();
            this.tblStakeholders = new HashSet<tblStakeholder>();
        }
    
        public int travelerId { get; set; }
        public string insurence_company { get; set; }
        public Nullable<bool> location { get; set; }
        public System.DateTime birthday { get; set; }
        public string gender { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblLocation> tblLocations { get; set; }
        public virtual tblUser tblUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblStakeholder> tblStakeholders { get; set; }
    }
}
